---
title: A personal blog by Juan Olvera
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
tagline: Frontend developer
email: jolvera@posteo.de
description: "Opinions and thoughts on web development, readings, and personal experiences."
baseurl: ''
url: 'https://jolvera.biz'
paginate: 5
author:
  name: Juan Olvera
twitter_username: _jolvera
github_username: j0lv3r4
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
