---
title: Juan Olvera
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
google_analytics: UA-49916340-3
permalink: pretty
tagline: Self-taught front-end developer & web standards enthusiastic.
email: jolvera@posteo.de
description: 'Juan Olvera''s personal website.

'
baseurl: ''
url: ''
paginate: 5
author:
  name: Juan Olvera
twitter_username: _jolvera
github_username: thinkxl
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
